-- 增量升级：近期热搜及管理员维护权限
-- 可安全用于现有线上数据库，不会删除商品、预定、分类或管理员数据。

create table if not exists public.hot_searches (
  id bigint generated by default as identity primary key,
  keyword text not null unique check (char_length(keyword) between 1 and 40),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.hot_searches enable row level security;

drop policy if exists hot_searches_public_read on public.hot_searches;
drop policy if exists hot_searches_admin_insert on public.hot_searches;
drop policy if exists hot_searches_admin_update on public.hot_searches;
drop policy if exists hot_searches_admin_delete on public.hot_searches;

create policy hot_searches_public_read on public.hot_searches for select to anon,authenticated
  using (is_active or (select public.is_admin()));
create policy hot_searches_admin_insert on public.hot_searches for insert to authenticated
  with check ((select public.is_admin()));
create policy hot_searches_admin_update on public.hot_searches for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy hot_searches_admin_delete on public.hot_searches for delete to authenticated
  using ((select public.is_admin()));

revoke all on public.hot_searches from anon,authenticated;
grant select on public.hot_searches to anon,authenticated;
grant insert,update,delete on public.hot_searches to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into public.hot_searches(keyword,sort_order) values
('教材',10),('蓝牙耳机',20)
on conflict (keyword) do nothing;

-- 把热搜表计入管理员后台的数据库资源统计。
create or replace function public.admin_resource_usage()
returns jsonb
language plpgsql
security definer
set search_path = public,storage,pg_temp
as $$
declare
  v_storage_count bigint := 0;
  v_storage_bytes bigint := 0;
  v_database_bytes bigint := 0;
  v_product_images bigint := 0;
  v_external_images bigint := 0;
begin
  if not public.is_admin() then raise exception '无权限'; end if;
  select count(*),coalesce(sum(case when coalesce(metadata->>'size','') ~ '^[0-9]+$' then (metadata->>'size')::bigint else 0 end),0)
  into v_storage_count,v_storage_bytes from storage.objects where bucket_id='product-images';
  select count(*) filter(where image_url is not null),count(*) filter(where image_url is not null and image_url not like '%/storage/v1/object/public/product-images/%')
  into v_product_images,v_external_images from public.products;
  v_database_bytes := pg_total_relation_size('public.profiles'::regclass)+pg_total_relation_size('public.categories'::regclass)+pg_total_relation_size('public.hot_searches'::regclass)+pg_total_relation_size('public.products'::regclass)+pg_total_relation_size('public.reservations'::regclass)+pg_total_relation_size('public.product_code_registry'::regclass)+pg_total_relation_size('public.site_settings'::regclass);
  return jsonb_build_object('storage_image_count',v_storage_count,'storage_bytes',v_storage_bytes,'database_bytes',v_database_bytes,'total_bytes',v_storage_bytes+v_database_bytes,'product_image_count',v_product_images,'external_image_count',v_external_images,'measured_at',now());
end;
$$;
revoke all on function public.admin_resource_usage() from public;
grant execute on function public.admin_resource_usage() to authenticated;

do $$
begin
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='hot_searches'
  ) then
    alter publication supabase_realtime add table public.hot_searches;
  end if;
end $$;
