-- 焦大师专闲置好物平台 / 全量重建脚本
-- 警告：本脚本会删除旧表及其中数据，然后重建并写入 10 件演示商品。
-- 请在 Supabase Dashboard -> SQL Editor 中完整执行。

create extension if not exists pgcrypto;

-- 1. 清理旧版对象
drop view if exists public.product_feed cascade;
drop view if exists public.public_profiles cascade;
drop view if exists public.public_site_settings cascade;
drop function if exists public.reserve_product(uuid, text, text) cascade;
drop function if exists public.reserve_product(uuid, text, text, text) cascade;
drop function if exists public.admin_set_reservation_status(uuid, text) cascade;
drop function if exists public.admin_set_user_disabled(uuid, boolean) cascade;
drop function if exists public.is_active_user() cascade;
drop function if exists public.is_admin() cascade;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.generate_connection_code() cascade;
drop function if exists public.issue_product_code(uuid,text) cascade;
drop function if exists public.assign_product_code() cascade;
drop function if exists public.admin_grant_admin(text) cascade;
drop function if exists public.admin_list_admins() cascade;
drop function if exists public.admin_resource_usage() cascade;
drop table if exists public.reservations cascade;
drop table if exists public.products cascade;
drop table if exists public.hot_searches cascade;
drop table if exists public.categories cascade;
drop table if exists public.product_code_registry cascade;
drop table if exists public.site_settings cascade;
drop table if exists public.profiles cascade;

-- 2. 数据表
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null default '管理员' check (char_length(nickname) between 1 and 40),
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 30),
  icon text not null default '📦' check (char_length(icon) between 1 and 16),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.hot_searches (
  id bigint generated by default as identity primary key,
  keyword text not null unique check (char_length(keyword) between 1 and 40),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 单行站点设置。管理员微信不会开放给前台查询。
create table public.site_settings (
  id boolean primary key default true check (id),
  admin_wechat text not null default '',
  announcement text not null default '' check (char_length(announcement) <= 2000),
  group_qr_url text,
  updated_at timestamptz not null default now()
);

-- 对接码永久台账不关联商品外键，因此删除商品后编码仍永久保留。
create table public.product_code_registry (
  code text primary key check (code ~ '^[0-9]{5}$'),
  product_id uuid not null unique,
  product_title text not null,
  issued_at timestamptz not null default now()
);

create or replace function public.issue_product_code(p_product_id uuid,p_product_title text)
returns text
language plpgsql
volatile
set search_path = public, pg_temp
as $$
declare v_code text; v_attempt integer := 0;
begin
  loop
    v_attempt := v_attempt + 1;
    if v_attempt > 1000 then raise exception '五位商品码已接近用尽，无法生成新编码'; end if;
    v_code := lpad((floor(random() * 100000)::integer)::text, 5, '0');
    begin
      insert into public.product_code_registry(code,product_id,product_title)
      values(v_code,p_product_id,p_product_title);
      return v_code;
    exception when unique_violation then
      -- 并发发布或历史编码冲突时继续生成，台账中的旧编码永不删除。
    end;
  end loop;
end;
$$;

create table public.products (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 120),
  description text not null default '' check (char_length(description) <= 3000),
  price numeric(10,2) not null check (price >= 0),
  condition text not null check (condition in ('全新','几乎全新','轻微使用痕迹','明显使用痕迹')),
  campus text not null check (char_length(campus) between 1 and 80),
  category_id bigint not null references public.categories(id) on delete restrict,
  connection_code text not null unique check (connection_code ~ '^[0-9]{5}$'),
  quantity integer not null default 1 check (quantity >= 1 and quantity <= 9999),
  sold_quantity integer not null default 0 check (sold_quantity >= 0 and sold_quantity <= quantity),
  status text not null default 'available' check (status in ('available','sold','removed')),
  image_url text,
  seller_contact text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.assign_product_code()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' then
    new.connection_code := public.issue_product_code(new.id,new.title);
  else
    new.connection_code := old.connection_code;
    update public.product_code_registry set product_title=new.title where product_id=new.id;
  end if;
  return new;
end;
$$;
create trigger products_assign_code before insert or update on public.products
for each row execute function public.assign_product_code();
revoke all on function public.issue_product_code(uuid,text) from public;
revoke all on function public.assign_product_code() from public;

create table public.reservations (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  buyer_name text not null check (char_length(buyer_name) between 1 and 40),
  contact text not null check (char_length(contact) between 1 and 120),
  note text not null default '' check (char_length(note) <= 1000),
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled')),
  created_at timestamptz not null default now()
);

create index products_category_idx on public.products(category_id);
create index products_created_idx on public.products(created_at desc);
create index reservations_product_idx on public.reservations(product_id);
create index reservations_created_idx on public.reservations(created_at desc);

insert into public.site_settings(id,admin_wechat) values(true,'') on conflict (id) do nothing;

-- 3. 管理员资料自动创建
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, nickname)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'nickname',''), split_part(coalesce(new.email,'管理员'),'@',1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 如果管理员账号在运行本脚本前已存在，为它补资料。
insert into public.profiles (id, nickname)
select id, split_part(coalesce(email,'管理员'),'@',1) from auth.users
on conflict (id) do nothing;

-- 4. 管理员权限判断
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select p.is_admin from public.profiles p where p.id = auth.uid()), false);
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- 5. 匿名访客原子预定
create or replace function public.reserve_product(
  p_product_id uuid,
  p_buyer_name text,
  p_contact text,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_status text;
  v_quantity integer;
  v_sold_quantity integer;
  v_reservation_id uuid;
  v_connection_code text;
  v_management_wechat text;
begin
  if nullif(btrim(p_buyer_name),'') is null then raise exception '请填写姓名'; end if;
  if char_length(btrim(p_buyer_name)) > 40 then raise exception '姓名过长'; end if;
  if nullif(btrim(p_contact),'') is null then raise exception '请填写联系方式'; end if;
  if char_length(btrim(p_contact)) > 120 then raise exception '联系方式过长'; end if;
  if char_length(coalesce(p_note,'')) > 1000 then raise exception '备注过长'; end if;

  select status,quantity,sold_quantity,connection_code into v_status,v_quantity,v_sold_quantity,v_connection_code from public.products where id = p_product_id for update;
  if not found then raise exception '商品不存在'; end if;
  if v_status <> 'available' or v_sold_quantity >= v_quantity then raise exception '该商品已售罄或不可购买'; end if;

  insert into public.reservations(product_id,buyer_name,contact,note)
  values (p_product_id,btrim(p_buyer_name),btrim(p_contact),coalesce(btrim(p_note),''))
  returning id into v_reservation_id;

  select admin_wechat into v_management_wechat from public.site_settings where id=true;
  return jsonb_build_object('reservation_id',v_reservation_id,'connection_code',v_connection_code,'seller_wechat',coalesce(v_management_wechat,''));
end;
$$;

revoke all on function public.reserve_product(uuid,text,text,text) from public;
grant execute on function public.reserve_product(uuid,text,text,text) to anon, authenticated;

-- 6. 管理员确认或取消预定，并同步商品状态
create or replace function public.admin_set_reservation_status(p_reservation_id uuid, p_status text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_product_id uuid;
  v_old_status text;
  v_quantity integer;
  v_sold_quantity integer;
  v_product_status text;
begin
  if not public.is_admin() then raise exception '无权限'; end if;
  if p_status not in ('confirmed','cancelled') then raise exception '无效状态'; end if;

  select product_id,status into v_product_id,v_old_status from public.reservations
  where id = p_reservation_id for update;
  if not found then raise exception '预定不存在'; end if;

  select quantity,sold_quantity,status into v_quantity,v_sold_quantity,v_product_status
  from public.products where id = v_product_id for update;
  if not found then raise exception '商品不存在'; end if;

  if v_old_status = p_status then return; end if;
  if p_status = 'confirmed' and v_sold_quantity >= v_quantity then
    raise exception '库存不足，无法确认成交';
  end if;

  update public.reservations set status = p_status where id = p_reservation_id;
  if p_status = 'confirmed' then
    update public.products set
      sold_quantity = sold_quantity + 1,
      status = case when sold_quantity + 1 >= quantity then 'sold' else 'available' end
    where id = v_product_id and status <> 'removed';
  else
    if v_old_status = 'confirmed' then
      update public.products set
        sold_quantity = greatest(sold_quantity - 1,0),
        status = case when status = 'removed' then 'removed' else 'available' end
      where id = v_product_id;
    end if;
  end if;
end;
$$;

revoke all on function public.admin_set_reservation_status(uuid,text) from public;
grant execute on function public.admin_set_reservation_status(uuid,text) to authenticated;

-- 7. RLS
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.hot_searches enable row level security;
alter table public.site_settings enable row level security;
alter table public.products enable row level security;
alter table public.reservations enable row level security;

create policy profiles_admin_read on public.profiles for select to authenticated
  using ((select public.is_admin()) or id = (select auth.uid()));

create policy categories_public_read on public.categories for select to anon,authenticated
  using (is_active or (select public.is_admin()));
create policy categories_admin_insert on public.categories for insert to authenticated
  with check ((select public.is_admin()));
create policy categories_admin_update on public.categories for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy categories_admin_delete on public.categories for delete to authenticated
  using ((select public.is_admin()));

create policy hot_searches_public_read on public.hot_searches for select to anon,authenticated
  using (is_active or (select public.is_admin()));
create policy hot_searches_admin_insert on public.hot_searches for insert to authenticated
  with check ((select public.is_admin()));
create policy hot_searches_admin_update on public.hot_searches for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy hot_searches_admin_delete on public.hot_searches for delete to authenticated
  using ((select public.is_admin()));

create policy site_settings_admin_read on public.site_settings for select to authenticated
  using ((select public.is_admin()));
create policy site_settings_admin_update on public.site_settings for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

alter table public.product_code_registry enable row level security;
create policy product_code_registry_admin_read on public.product_code_registry for select to authenticated
  using ((select public.is_admin()));

create policy products_public_read on public.products for select to anon,authenticated
  using (status <> 'removed' or (select public.is_admin()));
create policy products_admin_insert on public.products for insert to authenticated
  with check ((select public.is_admin()));
create policy products_admin_update on public.products for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy products_admin_delete on public.products for delete to authenticated
  using ((select public.is_admin()));

create policy reservations_admin_read on public.reservations for select to authenticated
  using ((select public.is_admin()));
create policy reservations_admin_delete on public.reservations for delete to authenticated
  using ((select public.is_admin()));

-- 前台商品视图：隐藏管理员联系方式，并汇总“几人想要”和剩余数量。
create view public.product_feed
with (security_invoker = false)
as
select
  p.id,p.title,p.description,p.price,p.condition,p.campus,p.category_id,p.status,
  p.image_url,p.is_demo,p.quantity,p.sold_quantity,
  greatest(p.quantity-p.sold_quantity,0) as available_quantity,
  count(r.id) filter (where r.status in ('pending','confirmed'))::integer as wanted_count,
  p.created_at,
  c.name as category_name,c.icon as category_icon
from public.products p
join public.categories c on c.id=p.category_id
left join public.reservations r on r.product_id=p.id
where p.status <> 'removed'
group by p.id,c.id;

-- 仅公开公告和群二维码，不暴露其他后台设置。
create view public.public_site_settings
with (security_invoker = false)
as select id,announcement,group_qr_url,updated_at from public.site_settings where id=true;

revoke all on public.profiles,public.categories,public.hot_searches,public.site_settings,public.product_code_registry,public.products,public.reservations from anon,authenticated;
grant select on public.categories to anon,authenticated;
grant select on public.hot_searches to anon,authenticated;
grant select on public.product_feed to anon,authenticated;
grant select on public.public_site_settings to anon,authenticated;
grant select on public.products to authenticated;
grant select on public.profiles,public.reservations,public.site_settings,public.product_code_registry to authenticated;
grant insert,update,delete on public.categories,public.products to authenticated;
grant insert,update,delete on public.hot_searches to authenticated;
grant update on public.site_settings to authenticated;
grant delete on public.reservations to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- 已登录管理员可把 Authentication 中已存在的邮箱账号提升为管理员。
create or replace function public.admin_grant_admin(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public,auth,pg_temp
as $$
declare v_user_id uuid; v_nickname text;
begin
  if not public.is_admin() then raise exception '无权限'; end if;
  select id into v_user_id from auth.users where lower(email)=lower(btrim(p_email));
  if v_user_id is null then raise exception '该邮箱尚未在 Authentication Users 中创建账号'; end if;
  insert into public.profiles(id,nickname,is_admin)
  select id,split_part(coalesce(email,'管理员'),'@',1),true from auth.users where id=v_user_id
  on conflict(id) do update set is_admin=true;
  select nickname into v_nickname from public.profiles where id=v_user_id;
  return jsonb_build_object('id',v_user_id,'email',lower(btrim(p_email)),'nickname',v_nickname);
end;
$$;
revoke all on function public.admin_grant_admin(text) from public;
grant execute on function public.admin_grant_admin(text) to authenticated;

create or replace function public.admin_list_admins()
returns table(id uuid,email text,nickname text,created_at timestamptz)
language plpgsql
security definer
set search_path = public,auth,pg_temp
as $$
begin
  if not public.is_admin() then raise exception '无权限'; end if;
  return query select p.id,u.email::text,p.nickname,p.created_at
  from public.profiles p join auth.users u on u.id=p.id
  where p.is_admin=true order by p.created_at;
end;
$$;
revoke all on function public.admin_list_admins() from public;
grant execute on function public.admin_list_admins() to authenticated;

create or replace function public.admin_resource_usage()
returns jsonb
language plpgsql
security definer
set search_path = public,storage,pg_temp
as $$
declare
  v_storage_count bigint := 0;
  v_storage_bytes bigint := 0;
  v_database_bytes bigint := 0;
  v_product_images bigint := 0;
  v_external_images bigint := 0;
begin
  if not public.is_admin() then raise exception '无权限'; end if;
  select count(*),coalesce(sum(case when coalesce(metadata->>'size','') ~ '^[0-9]+$' then (metadata->>'size')::bigint else 0 end),0)
  into v_storage_count,v_storage_bytes from storage.objects where bucket_id='product-images';
  select count(*) filter(where image_url is not null),count(*) filter(where image_url is not null and image_url not like '%/storage/v1/object/public/product-images/%')
  into v_product_images,v_external_images from public.products;
  v_database_bytes := pg_total_relation_size('public.profiles'::regclass)+pg_total_relation_size('public.categories'::regclass)+pg_total_relation_size('public.hot_searches'::regclass)+pg_total_relation_size('public.products'::regclass)+pg_total_relation_size('public.reservations'::regclass)+pg_total_relation_size('public.product_code_registry'::regclass)+pg_total_relation_size('public.site_settings'::regclass);
  return jsonb_build_object('storage_image_count',v_storage_count,'storage_bytes',v_storage_bytes,'database_bytes',v_database_bytes,'total_bytes',v_storage_bytes+v_database_bytes,'product_image_count',v_product_images,'external_image_count',v_external_images,'measured_at',now());
end;
$$;
revoke all on function public.admin_resource_usage() from public;
grant execute on function public.admin_resource_usage() to authenticated;

-- 8. 商品图片 Storage
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('product-images','product-images',true,5242880,array['image/webp'])
on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists product_images_public_read on storage.objects;
drop policy if exists product_images_admin_insert on storage.objects;
drop policy if exists product_images_admin_update on storage.objects;
drop policy if exists product_images_admin_delete on storage.objects;
drop policy if exists product_images_insert_own on storage.objects;
drop policy if exists product_images_update_own on storage.objects;
drop policy if exists product_images_delete_own on storage.objects;

create policy product_images_public_read on storage.objects for select to anon,authenticated
  using (bucket_id='product-images');
create policy product_images_admin_insert on storage.objects for insert to authenticated
  with check (bucket_id='product-images' and (select public.is_admin()));
create policy product_images_admin_update on storage.objects for update to authenticated
  using (bucket_id='product-images' and (select public.is_admin()))
  with check (bucket_id='product-images' and (select public.is_admin()));
create policy product_images_admin_delete on storage.objects for delete to authenticated
  using (bucket_id='product-images' and (select public.is_admin()));

-- 9. 默认分类
insert into public.categories(name,icon,sort_order) values
('教材','📚',10),('数码','💻',20),('生活','🏠',30),('服饰','👕',40),
('运动','🏀',50),('美妆','💄',60),('票务','🎫',70),('其他','📦',99);

insert into public.hot_searches(keyword,sort_order) values
('教材',10),('蓝牙耳机',20);

-- 10. 默认 10 件演示商品（后台可直接删除）
insert into public.products(id,title,description,price,condition,campus,category_id,status,quantity,image_url,seller_contact,is_demo,created_at) values
('10000000-0000-4000-8000-000000000001','高等数学教材与习题详解','大一高数教材，内页干净，附带配套习题册。',18,'轻微使用痕迹','新校区',(select id from public.categories where name='教材'),'available',3,null,'微信：demo_math',true,now()-interval '1 hour'),
('10000000-0000-4000-8000-000000000002','iPad Air 4 64G 天蓝色','功能正常，电池健康良好，带保护壳和充电器。',2280,'轻微使用痕迹','老校区',(select id from public.categories where name='数码'),'available',1,null,'微信：demo_ipad',true,now()-interval '2 hours'),
('10000000-0000-4000-8000-000000000003','宿舍护眼 LED 台灯','三档色温，亮度可调，宿舍自提。',35,'明显使用痕迹','新校区',(select id from public.categories where name='生活'),'available',2,null,'微信：demo_light',true,now()-interval '3 hours'),
('10000000-0000-4000-8000-000000000004','Nike 大容量运动背包','容量大，适合上课或短途出行。',88,'轻微使用痕迹','老校区',(select id from public.categories where name='运动'),'available',1,null,'微信：demo_bag',true,now()-interval '4 hours'),
('10000000-0000-4000-8000-000000000005','冬季轻薄羽绒服 M 码','黑色 M 码，保暖轻便，无破损。',129,'几乎全新','新校区',(select id from public.categories where name='服饰'),'available',2,null,'微信：demo_coat',true,now()-interval '5 hours'),
('10000000-0000-4000-8000-000000000006','线性代数复习资料','重点清晰，适合期末突击复习。',12,'轻微使用痕迹','老校区',(select id from public.categories where name='教材'),'available',5,null,'微信：demo_book',true,now()-interval '6 hours'),
('10000000-0000-4000-8000-000000000007','Sony 降噪蓝牙耳机','降噪和蓝牙功能正常，耳罩已清洁。',680,'明显使用痕迹','新校区',(select id from public.categories where name='数码'),'available',1,null,'微信：demo_headphone',true,now()-interval '7 hours'),
('10000000-0000-4000-8000-000000000008','小米 1.7L 电热水壶','烧水速度快，内胆无水垢。',28,'轻微使用痕迹','老校区',(select id from public.categories where name='生活'),'available',4,null,'微信：demo_kettle',true,now()-interval '8 hours'),
('10000000-0000-4000-8000-000000000009','校园音乐节门票两张','两张连号票，临时有事低价转让。',60,'全新','新校区',(select id from public.categories where name='票务'),'available',2,null,'微信：demo_ticket',true,now()-interval '9 hours'),
('10000000-0000-4000-8000-000000000010','Adidas 篮球鞋 42 码','鞋底磨损较少，已清洗消毒。',160,'轻微使用痕迹','老校区',(select id from public.categories where name='运动'),'available',1,null,'微信：demo_shoes',true,now()-interval '10 hours');

-- 11. Realtime
do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='products') then
    alter publication supabase_realtime add table public.products;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='categories') then
    alter publication supabase_realtime add table public.categories;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='hot_searches') then
    alter publication supabase_realtime add table public.hot_searches;
  end if;
end $$;

-- 12. 创建管理员
-- 先在 Supabase Dashboard -> Authentication -> Users 中创建一个邮箱用户，
-- 再执行 supabase/set-admin.sql；该文件已预填 sh770419@163.com。
